# File managed by pluginsync
sudo: true
language: go
go:
- 1.7.x
services:
  - docker
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
  - SNAP_VERSION: latest_build
    TEST_TYPE: large
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.7.x
    env: SNAP_VERSION=latest TEST_TYPE=large
  - go: 1.7.x
    env: SNAP_VERSION=latest_build TEST_TYPE=large
  - go: 1.7.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: K2AnEm2FcP0wEQ1rWJzkASpLUBHeICjwFxYGiq44HB3KTj/4G4MYtSIxYjWdG9C81sfCbC+wMHyWla8rRrVOxeMTBeJpoBNoX8wo3gAwetfA3DkVyN51xTsiHUa7yhjDjxD9scrGsJlwO+d9zyk63RU9rQGKxoDudlBvtfEat+Uke6Oq0rcUSXzqBF9ejLwscLYlFTmz+NfeACcvVqsB1Ht5RpR/VuqFXwpfmj/G+3YBx6RYQQempltL+JZUzT8UhHpQJf2sp148i/T/jqM4Agwmu398G61Jeu3t7ESDnvA37t+1hmmDq88AOveEp3pbOThCS/4ycbL2DRRns6aQnrZgBbVvHxY/ZdSWsyjVbqBQJCguo4BF0hyDdnfSi8mbkwcRf9XSSftwHxW0NyWPYhg/GASf2lKsrGG7UGZoUmMgb/jJ03sEdwjqzB+ICDa+Txhhmikxgwqfj0hyDXbHYmPNSwQ5TYI35upiEj8X8fERceFYgKGUCmphqsKtZq4iPcdKqJ4xBtHmKLutk2YqkDuKPUrx96/3kSTTF8OfaSU3+bipFcOyo48TLc/QEaag4MRoPU+L47xRwlSrZFFFrioVmFjxgY8yOoN0yRuc9XccMmmEzApa621OlzMjyduMw8UG5/+tXcmOOlcM1n2p+RqtJ/Vi0/9oyG7AxeP4mj8=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-influxdb
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: K2AnEm2FcP0wEQ1rWJzkASpLUBHeICjwFxYGiq44HB3KTj/4G4MYtSIxYjWdG9C81sfCbC+wMHyWla8rRrVOxeMTBeJpoBNoX8wo3gAwetfA3DkVyN51xTsiHUa7yhjDjxD9scrGsJlwO+d9zyk63RU9rQGKxoDudlBvtfEat+Uke6Oq0rcUSXzqBF9ejLwscLYlFTmz+NfeACcvVqsB1Ht5RpR/VuqFXwpfmj/G+3YBx6RYQQempltL+JZUzT8UhHpQJf2sp148i/T/jqM4Agwmu398G61Jeu3t7ESDnvA37t+1hmmDq88AOveEp3pbOThCS/4ycbL2DRRns6aQnrZgBbVvHxY/ZdSWsyjVbqBQJCguo4BF0hyDdnfSi8mbkwcRf9XSSftwHxW0NyWPYhg/GASf2lKsrGG7UGZoUmMgb/jJ03sEdwjqzB+ICDa+Txhhmikxgwqfj0hyDXbHYmPNSwQ5TYI35upiEj8X8fERceFYgKGUCmphqsKtZq4iPcdKqJ4xBtHmKLutk2YqkDuKPUrx96/3kSTTF8OfaSU3+bipFcOyo48TLc/QEaag4MRoPU+L47xRwlSrZFFFrioVmFjxgY8yOoN0yRuc9XccMmmEzApa621OlzMjyduMw8UG5/+tXcmOOlcM1n2p+RqtJ/Vi0/9oyG7AxeP4mj8=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-influxdb
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: releases
  api_key:
    secure: BxPzO6z768C2Sc6lijoRJNhMiL+HnUfcLWXB99WVQM++OaY+3t98EjabETvPfgCfl3gxyBrTnfn3umuj3dbFCSspptY+mnI/sjvvu3yfHMOPOGT+5yhPzBir+WA5GN4gAlAwvOoMYTUJf//An7b4Pa+98Tz52MJMtYvNPTtHmG8K4G6xhWRtkuIRp7jMrBJpp27RHBW03csBcX+wYwaPjTtRev4/VhnbQxquSq6EYWSXlxBPNt24y2zQJ5qcFs50XEz6FVzXp9S4rN9ngVbCHfdmwM/JxJCoeKgjDJErVb8VISNUHUHTin+4vtAU4ypheyWzxNcpGeCIECd7eNSwXFoCAZlmJIORDiWX3BlE7Hjxn+J3h0hw2EkOt6B/ReaY0fdg88xWZCGgUYiXTt4EQ7h0XugpQjTme/3w0efWufikwvgJi7EG1ITKTmTwvh8ps8IkU9WigIqcTacTLE051EIVhVsiUZJsuGgIdhQ3d3XCGS500GxNifrTxovOu2l0D3DKXoMbzt9quDHWSU28iJZsnAaYAKGt1M4rvahuC0KQ2d64Qcy4qIzoFc2O2FY9xqZGYAn0h0uPdzCgBj9FoHu3D/YEUDM7XTTws0hVT94/HpDcCiqd4zuE95cD0fHCjQfCWOBf9qMxbKWTAyHslMGtTwlIFL1IaAjLNpyI3SI=
  file:
    - release/snap-plugin-publisher-influxdb_linux_x86_64
    - release/snap-plugin-publisher-influxdb_darwin_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-publisher-influxdb
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
